Model -> Home Price Predication (Linear Regression)
1. Collect Data and Preprocess Dataset
2. EDA (Exploratory Data Analysis)
3. Features Exterction(selection)
4. Extract Input and Output columns(Independed and Depended variables)
5. Scalling
6. Train Test Split (Divide data into training and testing)
7. Train Model
8. Select proper model (Evaluate the model)
9. Deploy the model



In [18]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [19]:
from google.colab import files
files.upload()  # Choose your file from local system

Saving Home_Price_Dataset.csv to Home_Price_Dataset (1).csv


{'Home_Price_Dataset (1).csv': b'Sr_Number,Square_Feet,Price\r\n1,521,1402771\r\n2,534,1377542\r\n3,564,1590179\r\n4,630,1632115\r\n5,661,1725433\r\n6,689,1834772\r\n7,701,1902326\r\n8,741,2048543\r\n9,830,2109676\r\n10,837,2208326\r\n11,879,2345814\r\n12,955,2589037\r\n13,959,2515846\r\n14,966,2518860\r\n15,974,2586244\r\n16,992,2529572\r\n17,1062,2832740\r\n18,1100,2899639\r\n19,1146,3115170\r\n20,1202,3255707\r\n21,1247,3211774\r\n22,1263,3265120\r\n23,1269,3442366\r\n24,1275,3384150\r\n25,1291,3457823\r\n26,1315,3404581\r\n27,1360,3624295\r\n28,1378,3675514\r\n29,1455,3840520\r\n30,1475,3903131\r\n31,1495,3901527\r\n32,1516,4110766\r\n33,1521,3928780\r\n34,1576,4126688\r\n35,1582,4200806\r\n36,1595,4161469\r\n37,1629,4237902\r\n38,1630,4350940\r\n39,1652,4366401\r\n40,1680,4360505\r\n41,1684,4392770\r\n42,1715,4491861\r\n43,1738,4629798\r\n44,1767,4708527\r\n45,1775,4726801\r\n46,1794,4827980\r\n47,1797,4841999\r\n48,1863,4906811\r\n49,1867,4915479\r\n50,1890,5020675\r\n51,1978,528

In [20]:
df=pd.read_csv("Home_Price_Dataset.csv")

In [21]:
df.head()

Sr_Number  Square_Feet    Price
0          1          521  1402771
1          2          534  1377542
2          3          564  1590179
3          4          630  1632115
4          5          661  1725433

In [22]:
# Dataset Info
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [23]:
print("Shape:", df.shape)
print("\nData Types:\n", df.dtypes)
print("\nMissing Values:\n", df.isnull().sum())

Shape: (100, 3)

Data Types:
 Sr_Number      int64
Square_Feet    int64
Price          int64
dtype: object

Missing Values:
 Sr_Number      0
Square_Feet    0
Price          0
dtype: int64


In [24]:
 # Preprocess
df=df.drop('Sr_Number',axis='columns')
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [25]:
# EDA
# Find missing values
# Data types of columns
# value count of each columns
# Check duplicate values
print("\n Missing Values:\n")
print(df.isnull().sum())
print("\n Data type details of column:\n")
print(df.dtypes)
print("Duplicate values: ",df.duplicated().sum())


 Missing Values:

Square_Feet    0
Price          0
dtype: int64

 Data type details of column:

Square_Feet    int64
Price          int64
dtype: object
Duplicate values:  0


In [26]:
print("\n Value count of Each columns:\n")
print("Square Feet: ",df['Square_Feet'].value_counts())
print("Price: ",df['Price'].value_counts())


 Value count of Each columns:

Square Feet:  Square_Feet
521     1
534     1
564     1
630     1
661     1
       ..
3379    1
3388    1
3404    1
3419    1
3445    1
Name: count, Length: 100, dtype: int64
Price:  Price
1402771    1
1377542    1
1590179    1
1632115    1
1725433    1
          ..
8966622    1
8990132    1
8934926    1
8976947    1
9081538    1
Name: count, Length: 100, dtype: int64


In [27]:
X=df.drop('Price',axis='columns')
y=df.drop('Square_Feet',axis='columns')

In [28]:
X.shape
y.shape

(100, 1)

In [29]:
model=LinearRegression()

In [30]:
model.fit(X,y)

LinearRegression()

In [32]:
model.predict([[2500]]) #Predict for square meter to get prices of the home.

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6626631.81346664]])

In [33]:
model.score(X,y) # How accurate the model is on your dataset

0.999369407940212

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=20)

In [36]:
len(X_train)

80

In [38]:
len(X_test)

20

In [40]:
len(y_train)

80

In [41]:
X_train.shape


(80, 1)

In [44]:
X_train.head()

Square_Feet
27         1378
25         1315
98         3419
80         2891
65         2561

In [46]:
X_train.dtypes

Square_Feet    int64
dtype: object

In [51]:
y_train.head()

Price
27  3675514
25  3404581
98  8976947
80  7575139
65  6784845

In [55]:
y_train.dtypes

Price    int64
dtype: object

In [56]:
model.fit(X_train,y_train)

LinearRegression()

In [57]:
y_pred=model.predict(X_test)

In [58]:
len(y_pred)

20

In [59]:
len(y_test)

20

In [64]:
model.score(X_test,y_pred)

1.0

In [72]:
# For multiclass classification:
import numpy as np
from sklearn.metrics import classification_report

# If y_pred is a 2D array of probabilities
# Get index of highest probability as class label
y_pred_labels = np.argmax(y_pred, axis=1)

# Convert to class labels
y_pred_labels = np.argmax(y_pred, axis=1)

# Now it works
print(confusion_matrix(y_test, y_pred_labels))
print(classification_report(y_test, y_pred_labels))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
              precision    recall  f1-score   support


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

In [73]:
#model.predict([[2500]])
model.predict(pd.DataFrame([[3400]], columns=["Square_Feet"]))

array([[9012848.7674949]])

In [79]:
# Use a classification model instead, e.g.:
# LogisticRegression (for binary or multiclass classification)
# RandomForestClassifier, DecisionTreeClassifier, etc.
# from sklearn.linear_model import LogisticRegression
# model = LogisticRegression()
# model.fit(X_train, y_train)

# y_pred_proba = model.predict_proba(X_test)  # ✅ works
# y_pred = model.predict(X_test)              # ✅ class labels

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [87]:
m=model.coef_                      # The slope(s) of the regression line
b=model.intercept_                 # The y-intercept of the regression line
x=2500                             # Your input value (e.g., square feet, hours, etc.)
y=m*x+b                            # The prediction based on the linear equation
y

array([[-129.25923567, -128.34119865, -135.93510484, ..., -304.02166943,
        -302.26927488, -305.49035471],
       [-115.94416259, -115.02612558, -122.62003176, ..., -290.70659636,
        -288.95420181, -292.17528163],
       [ -82.42080558,  -81.50276857,  -89.09667475, ..., -257.18323935,
        -255.4308448 , -258.65192462],
       ...,
       [ 186.36885813,  187.28689514,  179.69298896, ...,   11.60642436,
          13.35881891,   10.13773908],
       [ 185.29479908,  186.2128361 ,  178.61892991, ...,   10.53236531,
          12.28475987,    9.06368004],
       [ 187.37031572,  188.28835273,  180.69444654, ...,   12.60788195,
          14.3602765 ,   11.13919667]])